### ISSUE TITLE
Panic in database UpdateProfile if firstname or lastname does not exist

### ISSUE THREAD

**Issue by mkwcat** [WiiLink24/wfc-server#16]
This error occurs in NiGHTS: Journey of Dreams (testing R7EPD00)
```
2023/11/29 03:29:12 N[GPCM:257/0343-5973-8625]: Command: updatepro
panic: can't scan into dest[5]: cannot scan null into *string

goroutine 40 [running]:
wwfc/database.UpdateProfile(0x12?, {0x8a00d0, 0xb265a0}, 0x101, 0x203a6d305b1b5d73?)
        /home/mkwcat/wwfc/wfc-server/database/user.go:57 +0x3ec
wwfc/gpcm.(*GameSpySession).updateProfile(...)
        /home/mkwcat/wwfc/wfc-server/gpcm/profile.go:64
wwfc/gpcm.(*GameSpySession).handleCommand(0xc000264200, {0x803356, 0x9}, {0xc0002b9310?, 0x2, 0x0?}, 0xc0000fbd18)
        /home/mkwcat/wwfc/wfc-server/gpcm/main.go:191 +0x37b
wwfc/gpcm.handleRequest({0x8a17b8?, 0xc00020a000})
        /home/mkwcat/wwfc/wfc-server/gpcm/main.go:167 +0x71f
created by wwfc/gpcm.StartServer in goroutine 7
        /home/mkwcat/wwfc/wfc-server/gpcm/main.go:72 +0x2e8
```

**Comment by mkwcat** [comment]
I'm not sure what the best way to fix this would be @noahpistilli

**Comment by noahpistilli** [comment]
I think what I did in the schema is set the lastname to an empty string by default. I had to do this or Mario Kart Wii would infinitely try to call `updatepro`
